### PR TITLE
[WIP] Linting

### PR DESCRIPTION
**Pull request by johnthepink**
This will bring airbnb linting, aside from double quotes, to our project. Oh man, this is going to take some work.

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
I'd love to help. Thoughts on divvying it up?

**Comment by johnthepink** [comment]
@jbaxleyiii yep, i'll make some comments later. There were initially like 6,000 problems. lint-fix was able to cut that in half. I'll get a list going.

**Comment by jbaxleyiii** [comment]
stew

**Comment by johnthepink** [comment]
@jbaxleyiii all our code is in `/imports`, so like 2499 of the 2500 errors are in there. Looks like they get reported out in alphabetical order by folder. So:

```
imports/blocks/accounts/ForgotPassword.js
...
imports/util/validate/index.js
```

You wanna start at the top and I'll start from the bottom and see where we get?

**Comment by johnthepink** [comment]
@jbaxleyiii rebased

**Comment by jbaxleyiii** [comment]
closing in favor of #1207

**Pull request closed without merging**
