### PR TITLE
Side card story

### PR DESCRIPTION
**Pull request by samclaridge**

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://1fa8aff5-aef5-4ace-874d-77e4ae653417.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzmann/branch/side-card-story/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by dcs619** [comment]
Sorry, something went wrong

**Comment by samclaridge** [comment]
@johnthepink do your job. Sorry, something went wrong

**Comment by johnthepink** [comment]
@samclaridge looks like we have a merge conflict. maybe a rebase?

**Comment by samclaridge** [comment]
@johnthepink I thought I had done that already. I just tried again, if that didn't work, then I must be doing it wrong.

**Comment by johnthepink** [comment]
@samclaridge looks good now. you probably did do it, but i merged some other PRs that caused conflicts to come back

**Comment by johnthepink** [comment]
thanks!

**Comment by dcs619** [comment]
reaction-6PDBZOJFBNi7u

**Pull request merged**
