### PR TITLE
Add FeedItem story

### PR DESCRIPTION
**Pull request by richarddubay**

### CODE REVIEW

**Comment by jbaxleyiii** [comment]
**[Storybook Hub](https://hub.getstorybook.io/)** is building storybooks for every commit in this PR.

**Latest Storybook: https://fc22f681-14f9-43e9-bde2-e7645fe5dcbb.sbook.io/**
<sub>( Visit [here](https://hub.getstorybook.io/app/github.com/NewSpring/Holtzmann/branch/add-feeditem-story/) for more info )</sub>

> _This comment is automatically added by Storybook Hub_

**Comment by richarddubay** [comment]
FWIW, the checks are failing for the same linting errors that David and I were seeing earlier.

**Comment by jbaxleyiii** [comment]
@richarddubay a few things:

- [ ] would you mind putting a max width on both of those cards? (maybe 480px)
- [ ] Let's change the parent story name to be `Cards`


I love this

**Comment by richarddubay** [comment]
This PR now contains the FeedItem story as well as tests for the FeedItem and MiniCard. Smooth.

**Comment by richarddubay** [comment]
PASSING BUILDS! 

giphy

**Comment by johnthepink** [comment]
@richarddubay looks like we have a merge conflict. maybe try rebasing again?

**Comment by richarddubay** [comment]
@johnthepink ^^ ?

**Comment by johnthepink** [comment]
hmmm. i wonder why it's still conflicting

**Pull request merged**
