### PR TITLE
Flow typing rebase

### PR DESCRIPTION
**Pull request by jbaxleyiii**
@johnthepink this is a rebased version of your branch

### CODE REVIEW

**Comment by johnthepink** [comment]
@jbaxleyiii i had turned off the `arrow-parens` eslint rule since flow needs the parens.

**Comment by jbaxleyiii** [comment]
@johnthepink hmm, I guess in the cherry-pick that got reset?

**Comment by jbaxleyiii** [comment]
I didn't think that would happen in a cherry-pick

**Comment by johnthepink** [comment]
@jbaxleyiii oh i see. Looks like the linting rule made it in, but maybe some of the files got missed in the rebase

**Comment by jbaxleyiii** [comment]
ah that makes sense, I'll clean that up once the SSR fix is out 👍

**Pull request merged**
